accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'login/$',
        auth_views.LoginView.as_view(template_name='accounts/login.html'),
        name='login'),
    url(r'logout/$',auth_views.LogoutView.as_view(),name='logout'),
    url(r'signup/$',views.SignUp.as_view(),name='signup'),
]

posts/urls.py
from django.urls import re_path
from . import views

app_name = 'posts'

urlpatterns = [
    re_path(r'^$',views.PostList.as_view(),name='all'),
    re_path(r'new/$',views.CreatePost.as_view(),name='create'),
    re_path(r'by/(?P<username>[-\w]+)/$',views.UserPosts.as_view(),name='for_user'),
    re_path(r'by/(?P<username>[-\w]+)/(?P<pk>\d+)/$',views.PostDetail.as_view(),name='single'),
    re_path(r'delete/(?P<pk>\d+)/$',views.DeletePost.as_view(),name='delete'),
]

spacesocial/urls.py
from django.contrib import admin
from django.urls import path,re_path,include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'),
    re_path(r'^accounts/',include('accounts.urls',namespace='accounts')),
    re_path(r'^accounts/',include('django.contrib.auth.urls')),
    re_path(r'^test/$',views.TestPage.as_view(),name='test'),
    re_path(r'^thanks/$',views.ThanksPage.as_view(),name='thanks'),
    re_path(r'^posts/',include('posts.urls',namespace='posts')),
    re_path(r'^groups/',include('groups.urls',namespace='groups')),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="UTF-8">
    <title>Space Social</title>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'spacesocial/css/master.css'%}">

</head>
<body>

    <nav class='navbar mynav' role='navigation' id='navbar'>
        <div class="container">
            <a class='navbar-brand mynav' href="{% url 'home' %}">Space Social</a>

            <ul class='nav navbar-nav navbar-right'>
                {% if user.is_authenticated %}
                    <li><a class="btn btn-simple" href="{% url 'posts:create' %}">Post</a></li>
                    <li><a class="btn btn-simple" href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a class="btn btn-simple" href="{% url 'groups:create' %}">Create Group</a></li>
                    <li><a class="btn btn-simple" href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                    <li><a class="btn btn-simple" href="{% url 'groups:all' %}">Groups</a></li>
                    <li><a class="btn btn-simple" href="{% url 'accounts:login' %}">Log in</a></li>
                    <li><a class="btn btn-simple" href="{% url 'accounts:signup' %}">Sign up</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mycontent">

        {% block content %}
        
        {% endblock %}

    </div>
</body>
</html>

templates/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Welcome</h1>
{% endblock %}

templates/test.html
{% extends "base.html" %}
{% block content %}
<h1>You are now logged in</h1>
{% endblock %}

templates/thanks.html
{% extends "base.html" %}
{% block content %}
<h1>Thanks for visiting, come back soon!!!</h1>
{% endblock %}